language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

services:
  - mongodb

matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
    - rvm: 1.9.3
      jdk: oraclejdk8
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
    - rvm: 2.0.0
      jdk: openjdk7
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
    - rvm: 2.0.0
      jdk: oraclejdk8
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
    - rvm: 2.1
      jdk: openjdk7
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
    - rvm: 2.1
      jdk: oraclejdk8
      env: CI="travis" JRUBY_OPTS="-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
